// Behavioural tests for the exported document's runtime, executed against a
// real DOM.
//
// The sibling `src/exportRuntime.test.ts` only asserts on the SOURCE TEXT of
// the runtime (it runs in the `node` project, no DOM). That caught nothing when
// 猫猫 reported 2026-07-29 that "到处以后所有的 Collapse 都不 work": the string
// 'data-snl-collapsible' was still present, so the text assertions stayed
// green while the script silently found no subtree to bind. These tests
// actually EXECUTE the runtime over markup shaped like the harvest output, so
// a regression in the wiring fails instead of passing quietly.
//
// Lives under `webview/` purely because that is the vitest project running in
// jsdom; the code under test is host-side.

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * The REAL script an exported document carries: SNL-Basics's bundled hover
 * implementation plus this Extension's wiring. Generated by
 * `npm run build:export-runtime`. Testing only the wiring half would miss the
 * whole point — hover behaviour now comes from SNL-Basics, not from here.
 */
const EXPORT_RUNTIME_JS = readFileSync(
  resolve(__dirname, '../../../media/exportRuntime.js'),
  'utf8'
);

/**
 * Markup shaped like `harvestLibraryHtml` output: every <button> already
 * stripped, only the data-* markers left. Covers BOTH collapsible surfaces —
 * the Entry outline (subtree is a direct child) and the `collapsible` block
 * renderer (subtree sits under a summary row) — plus a nested block, which is
 * the case that made a naive `host.children` scan wrong.
 */
const HARVESTED = `
<div id="outline" data-snl-collapsible="" data-snl-child-count="2">
  <div style="position:relative"><section>outline-row</section></div>
  <div data-snl-subtree=""><section>outline-child</section></div>
</div>
<div class="snl-collapsible-scope">
<div data-snl-collapsible-controls=""></div>
<div id="block" class="snl-collapsible" data-snl-collapsible="" data-snl-collapse-level="0"
     data-snl-child-count="2" data-snl-collapse-noun="parts" data-snl-collapsed="true"
     data-snl-initial-collapsed="true">
  <div class="snl-collapsible__summary"><section>block-summary</section></div>
  <div class="snl-collapsible__body" data-snl-subtree="">
    <div class="snl-collapsible__part">part1</div>
    <div id="nested" class="snl-collapsible" data-snl-collapsible="" data-snl-collapse-level="1"
         data-snl-child-count="1" data-snl-collapse-noun="part" data-snl-initial-collapsed="false">
      <div class="snl-collapsible__summary"><section>nested-summary</section></div>
      <div class="snl-collapsible__body" data-snl-subtree=""><div>nested-part</div></div>
    </div>
  </div>
</div>
<div id="peer" class="snl-collapsible" data-snl-collapsible="" data-snl-collapse-level="1"
     data-snl-child-count="1" data-snl-collapse-noun="part" data-snl-collapsed="true"
     data-snl-initial-collapsed="true">
  <div class="snl-collapsible__summary"><section>peer-summary</section></div>
  <div class="snl-collapsible__body" data-snl-subtree=""><div>peer-part</div></div>
</div>
</div>
<div class="snl-collapsible-scope" data-snl-collapsible-scope-label="Flat preview">
  <div id="empty-controls" data-snl-collapsible-controls=""></div>
  <div>leaf-only content</div>
</div>
<div data-entry-body="">
  <span data-scope="binder" data-bindref="b1" data-kind="rule" data-name="forall">
    <span data-kind="binder" data-bindref="b1" data-name="x">x</span>
    <span id="scoped-bvar" data-kind="bvar" data-bindref="b1" data-name="x">x</span>
  </span>
  <span data-scope="binder" data-bindref="b2" data-kind="rule" data-name="forall">
    <span data-kind="binder" data-bindref="b2" data-name="x">x</span>
    <span data-kind="bvar" data-bindref="b2" data-name="x">x</span>
  </span>
  <span id="orphan-bvar" data-kind="bvar" data-bindref="b9" data-name="y">y</span>
  <span data-kind="bvar" data-bindref="b9" data-name="y">y</span>
  <span id="sub-helper" data-kind="sub" data-name="helper">helper</span>
  <span id="partial-helper" data-kind="partial" data-name="legacy-helper">legacy helper</span>
</div>`;

/** The subtree THIS host owns — mirrors the runtime's ownership rule. */
function ownSubtree(host: HTMLElement): HTMLElement {
  const found = Array.from(
    host.querySelectorAll<HTMLElement>('[data-snl-subtree]')
  ).find((sub) => {
    let owner: HTMLElement | null = sub.parentElement;
    while (owner && owner !== host && !owner.hasAttribute('data-snl-collapsible')) {
      owner = owner.parentElement;
    }
    return owner === host;
  });
  if (!found) throw new Error('no owned subtree');
  return found;
}

function toggleOf(host: HTMLElement): HTMLButtonElement {
  const btn =
    host.querySelector<HTMLButtonElement>(':scope > .snl-collapsible__summary > button') ??
    host.querySelector<HTMLButtonElement>(':scope > button');
  if (!btn) throw new Error('no toggle');
  return btn;
}

const byId = (id: string): HTMLElement => {
  const el = document.getElementById(id);
  if (!el) throw new Error(`missing #${id}`);
  return el;
};

const click = (el: Element, init: MouseEventInit = {}): void => {
  el.dispatchEvent(new MouseEvent('click', { bubbles: true, ...init }));
};
const hover = (el: Element): void => {
  el.dispatchEvent(new MouseEvent('mousemove', { bubbles: true }));
};

describe('the exported runtime, executed', () => {
  beforeEach(() => {
    document.body.innerHTML = `<main class="snl-export">${HARVESTED}</main>`;
    // The runtime installs on DOMContentLoaded or immediately when the document
    // has already parsed; jsdom's document is 'complete' here, so eval suffices.
    // eslint-disable-next-line no-eval
    (0, eval)(EXPORT_RUNTIME_JS);
  });

  afterEach(() => {
    document.body.innerHTML = '';
    document.documentElement.lang = 'en';
    delete document.documentElement.dataset.snlColorScheme;
    delete (globalThis as Record<string, unknown>).__SNL_EXPORT_VARIANTS__;
  });

  it('builds a toggle for every collapsible host, on both surfaces', () => {
    expect(document.querySelectorAll('[data-snl-collapsible]')).toHaveLength(4);
    expect(document.querySelectorAll('button.snl-collapse-toggle')).toHaveLength(4);
  });

  it('collapses and re-expands an Entry outline row', () => {
    const host = byId('outline');
    const subtree = ownSubtree(host);
    expect(subtree.hidden).toBe(false);
    click(toggleOf(host));
    expect(subtree.hidden).toBe(true);
    click(toggleOf(host));
    expect(subtree.hidden).toBe(false);
  });

  it('finds the body of a collapsible BLOCK, whose subtree is not a direct child', () => {
    // The original runtime scanned `host.children` only, so this host bound no
    // subtree at all and its toggle was never built — the reported bug.
    const host = byId('block');
    const subtree = ownSubtree(host);
    click(toggleOf(host));
    expect(subtree.hidden).toBe(false);
  });

  it('mounts the block toggle inside the summary row so the gutter offset resolves', () => {
    // `left:-20px` is measured from the offset parent; only the summary row is
    // positioned (ui.css). Mounting on the host would throw the glyph off-block.
    expect(
      byId('block').querySelector(':scope > .snl-collapsible__summary > button')
    ).not.toBeNull();
  });

  it('honours the fold state the reader exported', () => {
    expect(ownSubtree(byId('block')).hidden).toBe(true);
    expect(ownSubtree(byId('outline')).hidden).toBe(false);
  });

  it('uses the noun the markup carries, not a hardcoded "sub-entries"', () => {
    expect(toggleOf(byId('block')).title).toBe('Expand 2 parts');
    expect(toggleOf(byId('nested')).title).toBe('Collapse 1 part');
    expect(toggleOf(byId('outline')).title).toBe('Collapse 2 sub-entries');
  });

  it('localizes generated toggle titles and accessibility names from the exported document locale', () => {
    document.body.innerHTML = `<main class="snl-export">${HARVESTED}</main>`;
    document.documentElement.lang = 'zh-CN';
    byId('block').setAttribute('data-snl-collapse-noun', '个部分');
    byId('nested').setAttribute('data-snl-collapse-noun', '个部分');
    // eslint-disable-next-line no-eval
    (0, eval)(EXPORT_RUNTIME_JS);

    expect(toggleOf(byId('block')).title).toBe('展开 2 个部分');
    expect(toggleOf(byId('block')).getAttribute('aria-label')).toBe('展开可折叠块 block-summary');
    expect(toggleOf(byId('outline')).title).toBe('收起 2 个子条目');
    expect(toggleOf(byId('outline')).getAttribute('aria-label')).toBe('收起');
  });

  it('keeps a nested collapsible independent of its parent', () => {
    click(toggleOf(byId('nested')));
    expect(ownSubtree(byId('nested')).hidden).toBe(true);
    expect(ownSubtree(byId('block')).hidden).toBe(true); // parent unchanged
  });


  it('Ctrl+Click toggles authored blocks at the same persisted absolute depth only', () => {
    expect(ownSubtree(byId('nested')).hidden).toBe(false);
    expect(ownSubtree(byId('peer')).hidden).toBe(true);
    expect(ownSubtree(byId('block')).hidden).toBe(true);

    click(toggleOf(byId('nested')), { ctrlKey: true });
    expect(ownSubtree(byId('nested')).hidden).toBe(true);
    expect(ownSubtree(byId('peer')).hidden).toBe(true);
    expect(ownSubtree(byId('block')).hidden).toBe(true);

    click(toggleOf(byId('nested')), { ctrlKey: true });
    expect(ownSubtree(byId('nested')).hidden).toBe(false);
    expect(ownSubtree(byId('peer')).hidden).toBe(false);
    expect(ownSubtree(byId('block')).hidden).toBe(true);
  });

  it('adds no bulk controls to an exported scope without foldable blocks', () => {
    expect(byId('empty-controls').querySelectorAll('button')).toHaveLength(0);
  });

  it('builds separate localized bulk controls for each exported render scope', () => {
    const controls = document.querySelector<HTMLElement>('[data-snl-collapsible-controls]')!;
    const expand = Array.from(controls.querySelectorAll('button')).find((button) =>
      button.textContent === 'Expand all') as HTMLButtonElement;
    const collapse = Array.from(controls.querySelectorAll('button')).find((button) =>
      button.textContent === 'Collapse all') as HTMLButtonElement;
    expect(expand.disabled).toBe(false);
    expect(collapse.disabled).toBe(false);

    click(expand);
    for (const id of ['block', 'nested', 'peer']) {
      expect(ownSubtree(byId(id)).hidden).toBe(false);
    }
    expect(expand.disabled).toBe(true);

    click(collapse);
    for (const id of ['block', 'nested', 'peer']) {
      expect(ownSubtree(byId(id)).hidden).toBe(true);
    }
    expect(collapse.disabled).toBe(true);
  });

  it('initializes lazy popover collapsibles once per inserted render scope', () => {
    vi.useFakeTimers();
    try {
      document.body.innerHTML = `
        <main class="snl-export">
          <div id="main-controls" data-snl-collapsible-controls=""></div>
          <div id="main-peer" data-snl-collapsible="" data-snl-collapse-level="1"
               data-snl-child-count="1" data-snl-collapsed="true">
            <div>main peer</div><div data-snl-subtree="">main hidden content</div>
          </div>
          <span id="popover-anchor" data-src="lazy-entry">lazy</span>
        </main>`;
      globalThis.__SNL_POPOVERS__ = {
        'lazy-entry': `
          <article data-entry-id="lazy-entry">
            <div class="snl-collapsible-scope" data-snl-collapsible-scope-label="Lazy preview">
              <div data-snl-collapsible-controls=""></div>
              <div id="popover-default" data-snl-collapsible="" data-snl-collapse-level="0"
                   data-snl-child-count="1" data-snl-collapse-noun="part" data-snl-collapsed="true"
                   data-snl-initial-collapsed="true">
                <div class="snl-collapsible__summary">default closed</div>
                <div data-snl-subtree=""><span>default hidden content</span>
                  <div id="popover-nested" data-snl-collapsible="" data-snl-collapse-level="1"
                       data-snl-child-count="1" data-snl-collapse-noun="part"
                       data-snl-initial-collapsed="false">
                    <div class="snl-collapsible__summary">nested open</div>
                    <div data-snl-subtree="">nested hidden content</div>
                  </div>
                </div>
              </div>
              <div id="popover-explicit" data-snl-collapsible="" data-snl-collapse-level="1"
                   data-snl-child-count="1" data-snl-collapse-noun="part" data-snl-collapsed="true"
                   data-snl-initial-collapsed="true">
                <div class="snl-collapsible__summary">explicit peer</div>
                <div data-snl-subtree="">explicit hidden content</div>
              </div>
            </div>
          </article>`
      };
      // Re-run over the replacement document after installing the lazy payload.
      // eslint-disable-next-line no-eval
      (0, eval)(EXPORT_RUNTIME_JS);

      const anchor = byId('popover-anchor');
      const show = (): HTMLElement => {
        anchor.dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));
        vi.advanceTimersByTime(1000);
        const popover = document.querySelector<HTMLElement>('[data-snl-popover="lazy-entry"]');
        if (!popover) throw new Error('popover did not open');
        return popover;
      };
      const hide = (popover: HTMLElement): void => {
        anchor.dispatchEvent(new MouseEvent('mouseout', { bubbles: true }));
        vi.advanceTimersByTime(180 + 150);
        expect(popover.isConnected).toBe(false);
      };

      let popover = show();
      expect(popover.querySelectorAll('button.snl-collapse-toggle')).toHaveLength(3);
      expect(popover.querySelectorAll('[data-snl-collapsible-controls] > button')).toHaveLength(2);
      expect(byId('main-controls').querySelectorAll('button')).toHaveLength(2);
      expect(ownSubtree(byId('popover-default')).hidden).toBe(true);
      expect(ownSubtree(byId('popover-nested')).hidden).toBe(false);
      expect(ownSubtree(byId('popover-explicit')).hidden).toBe(true);
      expect(popover.textContent).toContain('default hidden content');
      expect(popover.textContent).toContain('nested hidden content');
      expect(popover.textContent).toContain('explicit hidden content');

      // Plain click is local; Ctrl+Click applies only to peers at the same
      // authored depth inside this lazy render scope, never the main document.
      click(toggleOf(byId('popover-nested')));
      expect(ownSubtree(byId('popover-nested')).hidden).toBe(true);
      expect(ownSubtree(byId('popover-explicit')).hidden).toBe(true);
      click(toggleOf(byId('popover-nested')));
      click(toggleOf(byId('popover-nested')), { ctrlKey: true });
      expect(ownSubtree(byId('popover-nested')).hidden).toBe(true);
      expect(ownSubtree(byId('popover-explicit')).hidden).toBe(true);
      expect(ownSubtree(byId('main-peer')).hidden).toBe(true);

      const controls = popover.querySelector<HTMLElement>('[data-snl-collapsible-controls]')!;
      const expand = Array.from(controls.querySelectorAll('button')).find((button) =>
        button.textContent === 'Expand all')!;
      const collapse = Array.from(controls.querySelectorAll('button')).find((button) =>
        button.textContent === 'Collapse all')!;
      click(expand);
      for (const id of ['popover-default', 'popover-nested', 'popover-explicit']) {
        expect(ownSubtree(byId(id)).hidden).toBe(false);
      }
      click(collapse);
      for (const id of ['popover-default', 'popover-nested', 'popover-explicit']) {
        expect(ownSubtree(byId(id)).hidden).toBe(true);
      }

      const staleToggle = toggleOf(byId('popover-default'));
      hide(popover);
      popover = show();
      expect(popover.querySelectorAll('button.snl-collapse-toggle')).toHaveLength(3);
      expect(popover.querySelectorAll('[data-snl-collapsible-controls] > button')).toHaveLength(2);
      // A retained detached control must not reach into the replacement scope.
      click(staleToggle);
      expect(ownSubtree(byId('popover-default')).hidden).toBe(true);
      hide(popover);
      expect(document.querySelectorAll('[data-snl-popover]')).toHaveLength(0);
    } finally {
      delete globalThis.__SNL_POPOVERS__;
      vi.runOnlyPendingTimers();
      vi.useRealTimers();
    }
  });

  it('routes directly to a node panel with hash refresh, history, and unknown fallback', () => {
    window.history.replaceState(null, '', '#/node/node%20alpha');
    document.body.innerHTML = `
      <main class="snl-export">
        <section data-snl-route-id="node alpha"><article data-entry-id="entry-a">Alpha panel</article></section>
        <section data-snl-route-id="node/beta"><article data-entry-id="entry-b">Beta panel</article></section>
      </main>`;
    // eslint-disable-next-line no-eval
    (0, eval)(EXPORT_RUNTIME_JS);

    const alpha = document.querySelector<HTMLElement>('[data-snl-route-id="node alpha"]')!;
    const beta = document.querySelector<HTMLElement>('[data-snl-route-id="node/beta"]')!;
    expect(document.documentElement.getAttribute('data-snl-entry-route')).toBe('node alpha');
    expect(alpha.hasAttribute('data-snl-route-current')).toBe(true);
    expect(beta.hasAttribute('data-snl-route-current')).toBe(false);
    expect(alpha.querySelector<HTMLAnchorElement>(':scope > [data-snl-route-link]')?.hash)
      .toBe('#/node/node%20alpha');
    expect(alpha.querySelectorAll('[data-snl-route-link]')).toHaveLength(1);

    window.history.pushState(null, '', '#/node/node%2Fbeta');
    window.dispatchEvent(new HashChangeEvent('hashchange'));
    expect(document.documentElement.getAttribute('data-snl-entry-route')).toBe('node/beta');
    expect(alpha.hasAttribute('data-snl-route-current')).toBe(false);
    expect(beta.hasAttribute('data-snl-route-current')).toBe(true);

    window.history.pushState(null, '', '#/node/missing');
    window.dispatchEvent(new HashChangeEvent('hashchange'));
    expect(document.documentElement.hasAttribute('data-snl-entry-route')).toBe(false);
    expect(document.querySelector('[data-snl-route-not-found]')?.textContent)
      .toContain('missing');

    window.history.pushState(null, '', '#/node/%E0%A4%A');
    window.dispatchEvent(new HashChangeEvent('hashchange'));
    expect(document.documentElement.hasAttribute('data-snl-entry-route')).toBe(false);
    expect(document.querySelector('[data-snl-route-not-found]')?.textContent)
      .toContain('%E0%A4%A');

    window.history.pushState(null, '', '#/');
    window.dispatchEvent(new HashChangeEvent('hashchange'));
    expect(document.querySelector('[data-snl-route-not-found]')).toBeNull();
    expect(alpha.hasAttribute('data-snl-route-current')).toBe(false);
    expect(beta.hasAttribute('data-snl-route-current')).toBe(false);
  });

  it('extracts a deeply nested route into a flat single-node outlet and restores the outline', () => {
    window.history.replaceState(null, '', '#/node/child');
    document.body.innerHTML = `
      <main class="snl-export">
        <h1>Library</h1>
        <div data-snl-export-body>
          <div id="ancestor" data-snl-collapsible="" data-snl-child-count="1">
            <div data-snl-route-id="parent"><article data-entry-id="parent-entry">Parent</article></div>
            <div data-snl-subtree style="display:flex;flex-direction:column;gap:.75rem">
              <div id="indented-child" style="margin-left:40px;display:flex;gap:.75rem">
                <div data-snl-route-id="child"><article data-entry-id="child-entry">Child</article></div>
              </div>
            </div>
          </div>
        </div>
      </main>`;
    // eslint-disable-next-line no-eval
    (0, eval)(EXPORT_RUNTIME_JS);

    const body = document.querySelector<HTMLElement>('[data-snl-export-body]')!;
    const outlet = document.querySelector<HTMLElement>('[data-snl-route-outlet]')!;
    const child = document.querySelector<HTMLElement>('[data-snl-route-id="child"]')!;
    expect(body.hidden).toBe(true);
    expect(outlet.hidden).toBe(false);
    expect(child.parentElement).toBe(outlet);
    expect(child.hasAttribute('data-snl-route-current')).toBe(true);
    expect(outlet.querySelector('#indented-child')).toBeNull();
    expect(outlet.querySelector('#ancestor')).toBeNull();

    window.history.pushState(null, '', '#/');
    window.dispatchEvent(new HashChangeEvent('hashchange'));
    expect(body.hidden).toBe(false);
    expect(outlet.hidden).toBe(true);
    expect(document.querySelector('#indented-child > [data-snl-route-id="child"]')).toBe(child);
  });

  it('switches captured locale/theme variants from two top-right controls', () => {
    window.history.replaceState(null, '', '#/');
    document.body.innerHTML = `
      <main class="snl-export">
        <h1 data-snl-export-title>English title</h1>
        <p data-snl-export-subtitle>English subtitle</p>
        <div data-snl-export-body><section id="en-light">EN light</section></div>
      </main>`;
    (globalThis as Record<string, unknown>).__SNL_EXPORT_VARIANTS__ = {
      initialLocale: 'en',
      initialColorScheme: 'light',
      variants: [
        { locale: 'en', languageLabel: 'English', colorScheme: 'light', title: 'English title', subtitle: 'English subtitle', body: '<section id="en-light">EN light</section>', popovers: {} },
        { locale: 'en', languageLabel: 'English', colorScheme: 'dark', title: 'English title', subtitle: 'English subtitle', body: '<section id="en-dark">EN dark</section>', popovers: {} },
        { locale: 'zh-CN', languageLabel: '简体中文', colorScheme: 'light', title: '中文标题', subtitle: '中文副标题', body: '<section id="zh-light">中文浅色</section>', popovers: {} },
        { locale: 'zh-CN', languageLabel: '简体中文', colorScheme: 'dark', title: '中文标题', subtitle: '中文副标题', body: '<section id="zh-dark">中文深色</section>', popovers: {} }
      ]
    };
    // eslint-disable-next-line no-eval
    (0, eval)(EXPORT_RUNTIME_JS);

    const toolbar = document.querySelector<HTMLElement>('[data-snl-export-toolbar]')!;
    expect(toolbar).not.toBeNull();
    const theme = toolbar.querySelector<HTMLButtonElement>('[data-snl-theme-toggle]')!;
    const language = toolbar.querySelector<HTMLButtonElement>('[data-snl-language-trigger]')!;
    expect(theme.getAttribute('aria-label')).toBe('Switch to dark mode');
    expect(language.getAttribute('aria-label')).toBe('Language: English');

    click(theme);
    expect(document.documentElement.dataset.snlColorScheme).toBe('dark');
    expect(document.querySelector('#en-dark')).not.toBeNull();

    click(language);
    const zh = toolbar.querySelector<HTMLButtonElement>('[data-snl-language="zh-CN"]')!;
    expect(zh).not.toBeNull();
    click(zh);
    expect(document.documentElement.lang).toBe('zh-CN');
    expect(document.querySelector('#zh-dark')).not.toBeNull();
    expect(document.querySelector('[data-snl-export-title]')?.textContent).toBe('中文标题');
    expect(theme.getAttribute('aria-label')).toBe('切换到浅色模式');
  });

  it('keeps current sub helpers and legacy partial helpers outside hover selection', () => {
    hover(byId('sub-helper'));
    expect(document.querySelectorAll('.snl-single-hover')).toHaveLength(0);
    hover(byId('partial-helper'));
    expect(document.querySelectorAll('.snl-single-hover')).toHaveLength(0);
  });

  it('sets --snl-base-text-color so nested subtrees keep their base colour', () => {
    // 猫猫 2026-07-29: "悬浮的效果又出现子树没有正常不变色的 bug". The
    // stylesheet rule `.snl-single-hover [data-kind] { color: var(--snl-base-text-color) }`
    // is dead without this variable, so the whole hovered subtree took the
    // highlight colour. The hand-copied runtime never set it; SNL-Basics's
    // own implementation does, which is the point of reusing it.
    const body = document.querySelector<HTMLElement>('[data-entry-body]')!;
    body.style.color = 'rgb(17, 17, 17)';
    hover(byId('scoped-bvar'));
    expect(body.style.getPropertyValue('--snl-base-text-color')).toBe('rgb(17, 17, 17)');
  });

  it('limits bvar highlighting to the binder scope, matching the live panel', () => {
    hover(byId('scoped-bvar'));
    // Exactly the one bvar and one binder inside scope b1 — NOT the b2 pair.
    expect(document.querySelectorAll('.snl-bvar-scope')).toHaveLength(1);
    expect(document.querySelectorAll('.snl-binder-decl')).toHaveLength(1);
  });

  it('highlights nothing beyond the hovered node when no scope root carries the ref', () => {
    // 猫猫 2026-07-29: hovering a bvar lit up "全体". Cause: the runtime fell
    // back to the whole container as scope root, so every same-ref occurrence
    // in the entry lit up. defaultHighlightStrategy returns empty buckets here.
    hover(byId('orphan-bvar'));
    expect(document.querySelectorAll('.snl-bvar-scope')).toHaveLength(0);
    expect(document.querySelectorAll('.snl-binder-decl')).toHaveLength(0);
    expect(document.querySelectorAll('.snl-single-hover')).toHaveLength(1);
  });
});
