import * as vscode from 'vscode';
import { bind_preferences_panel_title } from './preferencesHost';
import { createHostTranslator, defineHostMessages } from './hostI18n';
import { read_extension_preferences } from './preferences';

const MESSAGES = defineHostMessages(
  { panelPoolTitle: 'SNL Relationship Graph', panelLibraryTitle: 'SNL Graph — {slug}', poolTitle: 'Relationship Graph', libraryTitle: 'Graph — {name}', noWorkspace: 'No workspace folder open.', refreshFailed: 'SNL graph refresh failed: {error}', libraryMissing: 'Library “{slug}” not found.', storageFailed: 'SNL Graph could not load entity storage: {error}', untitled: '(untitled)', unknown: 'unknown', popoverFailed: 'SNL Graph: failed to load popover entry: {error}' },
  { panelPoolTitle: 'SNL 关系图', panelLibraryTitle: 'SNL 图谱 — {slug}', poolTitle: '关系图', libraryTitle: '图谱 — {name}', noWorkspace: '未打开工作区文件夹。', refreshFailed: 'SNL 图谱刷新失败：{error}', libraryMissing: '未找到库“{slug}”。', storageFailed: 'SNL 图谱无法加载实体存储：{error}', untitled: '（无标题）', unknown: '未知', popoverFailed: 'SNL 图谱：无法加载弹出条目：{error}' }
);
const hostText = () => createHostTranslator(read_extension_preferences().language, MESSAGES);
import {
  listLibraries,
  readAllMacros,
  readEntries,
  readEntryKinds,
  readLibraryGraph,
  readMacroKinds,
  readRelationships,
  type EntryData,
  type EntryKind,
  type RelationshipData
} from './snlDoc';
import { buildPanelHtml, firstWorkspaceFolder, handlePanelNavMessage } from './panelUtil';

/**
 * Singleton graph-viewer panels (cat 2026-07-10 Phase 2).
 *
 * Renders the pool-wide relationship graph as a DAG-hierarchy layout with
 * no physics, hiding isolated nodes. Two scopes:
 *  - `pool` — every entry in the shared pool that appears on at least one
 *    edge in relationships.json.
 *  - `library:<slug>` — the induced subgraph over the library's entry set
 *    (endpoints ∈ library.entryIds).
 *
 * Message protocol with the webview (`snlGraph` bundle):
 *  - in  : `{ type: 'ready' }`
 *        | `{ type: 'openEntryInfoview', entryId }`
 *        | `{ type: 'editRelationship', id }`
 *        | (nav messages via handlePanelNavMessage)
 *  - out : `{ type: 'graph', scope, title, nodes[], edges[], warnings[] }`
 *
 * Auto-refresh: watches `.SNL_Doc/(config|entries|relationships).json`,
 * `libraries/<slug>/graph.json` (for scope=library), and macro packages
 * would refresh too but they don't affect the graph — kept narrow.
 */

interface GraphNodeOut {
  id: string;
  title: string;
  kind: string; // entry kind name (fallback: kind id)
  kindId: string;
  color: string; // stroke/border color from kind palette
  background: string;
}

interface GraphEdgeOut {
  id: string;
  from: string;
  to: string;
  label: string;
  /** True when this row was generated by macro-source scanning
   *  (label === "depends" && metadata.generator === "macro-source-scan"). */
  isDependency: boolean;
  /** True when metadata.isAtomic === true. Undefined for non-depends rows. */
  isAtomic: boolean | null;
}

type GraphScope = { mode: 'pool' } | { mode: 'library'; slug: string };

export class GraphPanel {
  private static readonly instances = new Map<string, GraphPanel>();
  private static readonly viewType = 'snlInfoviewGraph';

  private readonly panel: vscode.WebviewPanel;
  private readonly extensionUri: vscode.Uri;
  private readonly scope: GraphScope;
  private disposables: vscode.Disposable[] = [];
  private graphGeneration = 0;

  public static openPool(extensionUri: vscode.Uri): void {
    GraphPanel.open(extensionUri, { mode: 'pool' });
  }

  public static openForLibrary(extensionUri: vscode.Uri, slug: string): void {
    if (!slug) return;
    GraphPanel.open(extensionUri, { mode: 'library', slug });
  }

  private static open(extensionUri: vscode.Uri, scope: GraphScope): void {
    const column = vscode.ViewColumn.Active;
    const key = scope.mode === 'pool' ? 'pool' : `library:${scope.slug}`;
    const existing = GraphPanel.instances.get(key);
    if (existing) {
      existing.panel.reveal(column);
      void existing.pushGraph();
      return;
    }
    const title = scope.mode === 'pool'
      ? hostText()('panelPoolTitle')
      : hostText()('panelLibraryTitle', { slug: scope.slug });
    const panel = vscode.window.createWebviewPanel(
      GraphPanel.viewType,
      title,
      column,
      {
        enableScripts: true,
        retainContextWhenHidden: true,
        localResourceRoots: [vscode.Uri.joinPath(extensionUri, 'media')]
      }
    );
    bind_preferences_panel_title(panel, () => scope.mode === 'pool'
      ? hostText()('panelPoolTitle')
      : hostText()('panelLibraryTitle', { slug: scope.slug }));
    GraphPanel.instances.set(key, new GraphPanel(panel, extensionUri, scope));
  }

  private constructor(
    panel: vscode.WebviewPanel,
    extensionUri: vscode.Uri,
    scope: GraphScope
  ) {
    this.panel = panel;
    this.extensionUri = extensionUri;
    this.scope = scope;

    const title = scope.mode === 'pool'
      ? hostText()('panelPoolTitle')
      : hostText()('panelLibraryTitle', { slug: scope.slug });

    this.panel.webview.html = buildPanelHtml(
      this.extensionUri,
      this.panel.webview,
      'snlGraph',
      title, this.disposables);

    this.panel.webview.onDidReceiveMessage(
      (m) => this.handleMessage(m),
      null,
      this.disposables
    );

    this.installWatcher();

    this.panel.onDidDispose(() => this.dispose(), null, this.disposables);
  }

  private installWatcher(): void {
    const root = firstWorkspaceFolder();
    if (!root) return;
    const patterns: vscode.GlobPattern[] = [
      new vscode.RelativePattern(root, '.SNL_Doc/config.json'),
      new vscode.RelativePattern(root, '.SNL_Doc/entries.json'),
      new vscode.RelativePattern(root, '.SNL_Doc/entries/*.json'),
      new vscode.RelativePattern(root, '.SNL_Doc/relationships.json'),
      new vscode.RelativePattern(root, '.SNL_Doc/term_macros/*.json'),
      new vscode.RelativePattern(root, '.SNL_Doc/packages/*.json'),
      new vscode.RelativePattern(root, '.SNL_Doc/macros/*.json')
    ];
    if (this.scope.mode === 'library') {
      patterns.push(
        new vscode.RelativePattern(
          root,
          `.SNL_Doc/libraries/${this.scope.slug}/graph.json`
        )
      );
    }
    let refreshTimer: ReturnType<typeof setTimeout> | undefined;
    const refresh = (): void => {
      if (refreshTimer) clearTimeout(refreshTimer);
      refreshTimer = setTimeout(() => {
        refreshTimer = undefined;
        void this.pushGraph();
      }, 120);
    };
    this.disposables.push({ dispose: () => { if (refreshTimer) clearTimeout(refreshTimer); } });
    for (const p of patterns) {
      const w = vscode.workspace.createFileSystemWatcher(p);
      w.onDidCreate(refresh, null, this.disposables);
      w.onDidChange(refresh, null, this.disposables);
      w.onDidDelete(refresh, null, this.disposables);
      this.disposables.push(w);
    }
  }

  private async handleMessage(message: unknown): Promise<void> {
    if (await handlePanelNavMessage(message, () => this.pushGraph())) return;
    const msg = message as { type?: string } | undefined;
    if (!msg || typeof msg.type !== 'string') return;
    switch (msg.type) {
      case 'ready':
        await this.pushGraph();
        return;
      case 'openEntryInfoview': {
        const id = (msg as { entryId?: unknown }).entryId;
        if (typeof id === 'string' && id.trim()) {
          void vscode.commands.executeCommand(
            'snlDoc.openEntryInfoview',
            id.trim()
          );
        }
        return;
      }
      case 'editRelationship': {
        const id = (msg as { id?: unknown }).id;
        if (typeof id === 'string' && id.trim()) {
          void vscode.commands.executeCommand(
            'snlDoc.editRelationship',
            id.trim()
          );
        }
        return;
      }
      case 'requestEntryDetails': {
        // Popover full-Entry render. Same protocol as InfoviewPanel so
        // the shared HoverPopoverProvider works unchanged (cat 2026-07-10).
        const id = (msg as { entryId?: unknown }).entryId;
        if (typeof id === 'string' && id.trim()) {
          await this.pushPopoverEntryDetails(id.trim());
        }
        return;
      }
    }
  }

  private async pushGraph(): Promise<void> {
    const generation = ++this.graphGeneration;
    const root = firstWorkspaceFolder();
    if (!root) {
      void this.panel.webview.postMessage({
        type: 'graph',
        scope: this.scope,
        title:
          this.scope.mode === 'pool'
            ? hostText()('poolTitle')
            : hostText()('libraryTitle', { name: this.scope.slug }),
        nodes: [],
        edges: [],
        warnings: [hostText()('noWorkspace')]
      });
      return;
    }
    const warnings: string[] = [];
    let entries: EntryData[];
    let kinds: EntryKind[];
    let rels: RelationshipData[];
    try {
      [entries, kinds, rels] = await Promise.all([
        readEntries(root),
        readEntryKinds(root),
        readRelationships(root)
      ]);
    } catch (err) {
      if (generation !== this.graphGeneration) return;
      const message = hostText()('refreshFailed', { error: err instanceof Error ? err.message : String(err) });
      void this.panel.webview.postMessage({
        type: 'graphError',
        scope: this.scope,
        title: this.scope.mode === 'pool' ? hostText()('poolTitle') : hostText()('libraryTitle', { name: this.scope.slug }),
        message
      });
      void vscode.window.showErrorMessage(message);
      return;
    }

    // Scope filter: for a library, restrict endpoints to that library's
    // entry set (induced subgraph).
    let allowedIds: Set<string> | null = null;
    let displayTitle: string;
    if (this.scope.mode === 'library') {
      const scopeSlug = this.scope.slug;
      displayTitle = hostText()('libraryTitle', { name: scopeSlug });
      try {
        const libraries = await listLibraries(root);
        if (generation !== this.graphGeneration) return;
        const lib = libraries.find((l) => l.slug === scopeSlug);
        if (!lib) {
          warnings.push(hostText()('libraryMissing', { slug: scopeSlug }));
          void this.panel.webview.postMessage({
            type: 'graph',
            scope: this.scope,
            title: displayTitle,
            nodes: [],
            edges: [],
            warnings
          });
          return;
        }
        displayTitle = hostText()('libraryTitle', { name: lib.title });
        const graphResult = await readLibraryGraph(root, scopeSlug);
        if (generation !== this.graphGeneration) return;
        if (graphResult.status === 'error') {
          const message = hostText()('refreshFailed', { error: graphResult.message });
          void this.panel.webview.postMessage({
            type: 'graphError', scope: this.scope, title: displayTitle, message
          });
          void vscode.window.showErrorMessage(message);
          return;
        }
        allowedIds = new Set<string>();
        if (graphResult.status === 'ok') {
          for (const node of graphResult.result.graph.nodes) {
            if (node.label !== 'Entry') continue;
            const eid = (node.props as { entryId?: unknown } | undefined)
              ?.entryId;
            if (typeof eid === 'string' && eid) allowedIds.add(eid);
          }
        }
      } catch (error) {
        if (generation !== this.graphGeneration) return;
        const message = hostText()('refreshFailed', { error: error instanceof Error ? error.message : String(error) });
        void this.panel.webview.postMessage({
          type: 'graphError', scope: this.scope, title: displayTitle, message
        });
        void vscode.window.showErrorMessage(message);
        return;
      }
    } else {
      displayTitle = hostText()('poolTitle');
    }

    // Build filtered edge set + participating node set. "Isolated" here
    // means: not the endpoint of any edge in the (filtered) view. Cat
    // 2026-07-10: hide isolated nodes.
    const kindById = new Map<string, EntryKind>();
    for (const k of kinds) kindById.set(k.id, k);
    const entryById = new Map<string, EntryData>();
    for (const e of entries) entryById.set(e.id, e);

    const edges: GraphEdgeOut[] = [];
    const participating = new Set<string>();
    for (const r of rels) {
      if (allowedIds && !(allowedIds.has(r.from) && allowedIds.has(r.to))) {
        continue;
      }
      edges.push({
        id: r.id,
        from: r.from,
        to: r.to,
        label: r.label,
        // Auto-managed = generator tag AND label ∈ {depends, uses_context}.
        // The graph filter treats them uniformly so cat's atomic-only
        // toggle covers both kinds (cat 2026-07-10).
        isDependency:
          (r.label === 'depends' || r.label === 'uses_context') &&
          r.metadata !== null &&
          typeof r.metadata === 'object' &&
          (r.metadata as { generator?: unknown }).generator ===
            'macro-source-scan',
        isAtomic:
          (r.label === 'depends' || r.label === 'uses_context') &&
          r.metadata !== null &&
          typeof r.metadata === 'object' &&
          typeof (r.metadata as { isAtomic?: unknown }).isAtomic === 'boolean'
            ? ((r.metadata as { isAtomic: boolean }).isAtomic)
            : null
      });
      participating.add(r.from);
      participating.add(r.to);
    }

    const nodes: GraphNodeOut[] = [];
    for (const id of participating) {
      const e = entryById.get(id);
      const kind = e ? kindById.get(e.kind) : undefined;
      nodes.push({
        id,
        title: e ? e.title || hostText()('untitled') : `⚠ ${id}`,
        kind: kind ? kind.name : e ? e.kind : hostText()('unknown'),
        kindId: e ? e.kind : '',
        color: kind ? kind.coloring.stroke : '#888888',
        background: kind ? kind.coloring.background : 'transparent'
      });
    }
    nodes.sort((a, b) => a.id.localeCompare(b.id));

    // Full pool as EntryOption + workspace macros, shipped so the
    // popover EntryRender (via HoverPopoverProvider) can resolve
    // cross-entry macro sources + render the SNL body faithfully.
    // Cat 2026-07-10.
    const entryOptions = entries.map((e) => ({
      id: e.id,
      title: e.title ?? '',
      hasContent:
        typeof e.content?.snl === 'string' && e.content.snl.trim().length > 0,
      snl: typeof e.content?.snl === 'string' ? e.content.snl : undefined
    }));
    // Independent reads run concurrently (cat 2026-07-25: panels felt slow).
    let allMacros: Awaited<ReturnType<typeof readAllMacros>>;
    let macroKinds: Awaited<ReturnType<typeof readMacroKinds>>;
    try {
      [allMacros, macroKinds] = await Promise.all([
        readAllMacros(root),
        readMacroKinds(root)
      ]);
    } catch (error) {
      if (generation !== this.graphGeneration) return;
      const message = hostText()('storageFailed', { error: error instanceof Error ? error.message : String(error) });
      void this.panel.webview.postMessage({
        type: 'graphError', scope: this.scope, title: displayTitle, message
      });
      void vscode.window.showErrorMessage(message);
      return;
    }
    if (generation !== this.graphGeneration) return;

    void this.panel.webview.postMessage({
      type: 'graph',
      scope: this.scope,
      title: displayTitle,
      nodes,
      edges,
      warnings,
      entryOptions,
      macros: allMacros,
      macroKinds
    });
  }

  private async pushPopoverEntryDetails(id: string): Promise<void> {
    const root = firstWorkspaceFolder();
    if (!root) return;
    try {
      const entries = await readEntries(root);
      const entry = entries.find((e) => e.id === id);
      if (!entry) {
        void this.panel.webview.postMessage({
          type: 'popoverEntryDetails',
          entryId: id,
          entry: null,
          kind: null
        });
        return;
      }
      const kinds = await readEntryKinds(root);
      const kind = kinds.find((k) => k.id === entry.kind) ?? null;
      void this.panel.webview.postMessage({
        type: 'popoverEntryDetails',
        entryId: id,
        entry,
        kind
      });
    } catch (err) {
      const text = err instanceof Error ? err.message : String(err);
      vscode.window.showErrorMessage(
        hostText()('popoverFailed', { error: text })
      );
    }
  }

  public dispose(): void {
    const key =
      this.scope.mode === 'pool' ? 'pool' : `library:${this.scope.slug}`;
    GraphPanel.instances.delete(key);
    this.panel.dispose();
    while (this.disposables.length) {
      const d = this.disposables.pop();
      if (d) d.dispose();
    }
  }
}
